### ISSUE TITLE
Unclassified domain

### ISSUE THREAD

**Issue by leotiger** [leotiger/grav-plugin-babel#9]
Based on a conversation with @rhukster and his testing the need for a new virtual domain emerged: the "unclassified" domain. This domain collects all variables not attached to a domain namespace, e.g. PLUGIN_ADMIN, PLUGIN_BABEL. There are only a few of these variables directly attached to the language root and most cases occur in the context of theme variables:

```
en:
    SITE:
        COPYRIGHT: the copyright information
        COPYRIGHT_YEAR: copyright year
    TWEET: Tweet
    BIRD: Duck
``` 

In the former example not only the TWEET or the BIRD variable are problematic but also the SITE variable. Without deeper tracking mechanisms BABEL, in the current version will classify SITE as a domain while SITE in fact belongs to a THEME domain. As stated, this affects only few variables, mostly in the context of themes.

On the contrary it's common practice in plugins to declare the scope of defined variables:

```
en:
    PLUGIN_SCOPE:
        SITE:
            COPYRIGHT: the copyright information
            COPYRIGHT_YEAR: copyright year
        TWEET: Tweet
        BIRD: Duck
``` 

This makes a big difference as you can deduce. TWEET is now perfectly classified as a variable in the context of the plugin Scope. For this reason Babel introduced with version 1.0.4 the notion of *unclassified*, but we are working on a context tracking that will allow us to box root level variables in context:

* system
* theme
* instance

The rest of unclassified root level variables necessarily run in from a plugin and we will track this as well. What does this mean?

In the context of exports, plugins that include definitions out of the scope of the shared plugin namespace as their ancestor are currently not included in exports:

```
en:
  PLUGIN_SCOPE:
    SITE:
      COPYRIGHT: the copyright information
      COPYRIGHT_YEAR: copyright year
    TWEET: Tweet
    BIRD: Duck
  DESCRIPTION: Scope offers some context data
``` 

The DESCRIPTION variable would currently be boxed under "unclassified" and in fact, from a logical viewpoint, it's unclassified because it's not specific enough. A theme variable with an identical identifier would overwrite the particular description for the Scope plugin.

Another side effect of the bad practice in declaring theme variables without a domain, institutionalized in GRAV, is that BABEL currently does not offer a dedicated theme domain which would allow exports as well. This will change in the near future.

And a final note: The solution we will offer will probably cover more than 99% of the "unclassified" cases. Nevertheless, it will be difficult to guarantee a 100% solution, especially for cases where two root level variables with the same key are declared in different contexts.
